services:
  mysql:
    container_name: mysql
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USERNAME: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY: 1
    ports:
      - '3306:3306'
    networks:
      - backend
    volumes:
      - data-mysql:/var/lib/mysql
    
  rabbitmq:
    image: 'rabbitmq:4.0.2'
    environment:
      RABBITMQ_DEFAULT_USER: '${RABBITMQ_DEFAULT_USER}'
      RABBITMQ_DEFAULT_PASS: '${RABBITMQ_DEFAULT_PASS}'
    ports:
      - '5672:5672'
    networks:
      - backend
  redis:
    image: 'redis:8.0-M01'
    ports:
      - '6379:6379'
    networks:
      - backend
  
networks:
  backend:
    driver: bridge
volumes:
  data-mysql:
    driver: local